---
config:
  theme: default
  xyChart:
    width: 820
    height: 380
    titleFontSize: 16
    xAxis:
      labelFontSize: 14
---
xychart-beta
    title "Enrichment occurrences per step (change-cost canary)"
    x-axis ["master", "R1b", "R1c", "R1d", "R1e", "R1f", "R2b", "final"]
    y-axis "occurrences" 40 --> 80
    bar [69, 69, 68, 53, 72, 72, 72, 72]
    line [69, 69, 68, 53, 72, 72, 72, 72]
