#!/usr/bin/env python
"""
Dev-only instrument (repo-root ``tools/``, NOT shipped -- see ``pyproject.toml``'s
``[tool.hatch.build.targets.wheel] packages`` list, which does not include this
directory) that the TOO-45 architecture-refactoring loop runs every iteration.

Stdlib only -- this project's runtime carries no third-party dependency, and this
tool follows the same discipline so it never needs one either.

Every number this module prints is an INSTRUMENT, not a TARGET. A predicate or
metric going the "right" way is evidence to bring to a human or a judge subagent,
never a self-sufficient stopping condition -- see the TOO-45 execution plan,
section 7 ("Anti-gaming prohibitions") and section 8 (the two judges). In
particular ``--metrics``' fan-in figure is demonstrably misleading on this
codebase (see the ``--metrics`` docstring below) and must never be read alone.

Four modes
----------
``--layers``
    Validate every module under ``toolguard/`` against the ``[architecture]``
    block of ``.pyscn.toml`` (the single source of truth for the layer map).
    Reports completeness (every module maps to exactly one layer -- pyscn
    itself silently stops validating an unmapped module while its compliance
    score stays plausible, and never names the module; this closes that hole)
    and direction (every import that violates the from-layer's allow list).

``--predicates``
    Emit the COMPONENT diagnostics behind each TOO-45 step predicate (R1, R2,
    R3, R5, R6), plus the enrichment-footprint tracked diagnostic (not a
    predicate). Add ``--json`` for machine consumption; the judges read the
    components, not a bare boolean. Every generated file (banner-detected, see
    below) is excluded from every predicate here and named explicitly in the
    output -- a predicate only satisfiable by hand-editing generated code is a
    trap this project's own rules forbid walking into. R1 additionally
    excludes ``toolguard/parser/`` (out of scope for this ticket), also named
    explicitly.

Generated code
    A file whose first ~10 lines carry a banner such as "generated from",
    "DO NOT EDIT", "@generated", or "autogenerated" (see
    :data:`GENERATED_FILE_MARKERS`) is detected by CONTENT, never by a
    hardcoded filename -- a hardcoded path silently stops protecting a second
    generated file the moment one is added. Excluded from ``--predicates`` and
    ``--metrics``; NOT excluded from ``--layers``, whose job is validating the
    real import graph, which a generated file is still part of.

``--metrics``
    History-based metrics from ``git log``, grouped by logical change (the
    ``TOO-nn`` ticket token in the full commit message, not by raw commit --
    grouping by ticket is what removes the commit-splitting gaming vector).

``--guard``
    The deterministic half of the loop's safety inspector: fails on an
    out-of-scope file touch, a shrinking test count, a new runtime dependency,
    or a failing lint/format/doc-link check. Also evaluates a fixed CANARY set
    through the LIVE toolguard hook binary and asserts the expected verdict
    still comes back -- the loop's own guard rules
    (``.claude/toolguard_hook.toml`` and ``~/.toolguard/rules/git.rules.toml``)
    are NOT version-controlled here (one is a symlink into an external dotfiles
    repo, left deliberately uncommitted; the other lives outside any repo
    entirely), and this project's own ``no_match_fallback = "allow_with_no_
    warnings"`` means a lost deny rule fails OPEN and SILENT -- nothing else
    would notice. Cheap, fast, no network (the canary check runs a local
    subprocess, nothing more). ``--guard-canaries-only`` runs just the canary
    check, skipping the diff/test-count/dependency/lint checks.

Usage::

    uv run python tools/architecture_fitness.py --layers
    uv run python tools/architecture_fitness.py --predicates --json
    uv run python tools/architecture_fitness.py --metrics
    uv run python tools/architecture_fitness.py --guard --since HEAD
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import subprocess
import sys
import tomllib
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, FrozenSet, Iterable, List, Optional, Sequence, Set, Tuple

#: Repo root, following the convention already used by ``tools/corpus_build.py``.
REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLGUARD_DIR = REPO_ROOT / "toolguard"
PYSCN_TOML = REPO_ROOT / ".pyscn.toml"


# =============================================================================
# Shared: python file discovery and module-path helpers
# =============================================================================


def iter_python_files(directory: Path) -> Iterable[Path]:
    """
    Yield every ``*.py`` file under *directory*, skipping ``__pycache__``.

    Deterministic order (sorted) so output is stable run to run, which matters
    for a tool a loop diffs between iterations.
    """
    yield from sorted(
        p for p in directory.rglob("*.py") if "__pycache__" not in p.parts
    )


#: Substrings (checked lowercased) that mark a file as machine-generated. Matched
#: against a BANNER near the top of the file, never a filename -- a hardcoded
#: filename check silently stops working the moment a second generated file is
#: added, which is the same failure class as the git-rules harness that once
#: validated a stale copy instead of the governing file (see the TOO-45 decision
#: log). ``toolguard/parser/bash_parser.py`` (canopy output from
#: ``bash_parser.peg``, ~6,500 lines, first line literally "This file was
#: generated from bash_parser.peg") is the known case today, but this must keep
#: working if a second generated file ever appears anywhere else in the tree.
GENERATED_FILE_MARKERS = (
    "generated from",
    "do not edit",
    "@generated",
    "autogenerated",
)

#: How many leading lines to scan for a generated-code banner. Generous enough
#: for a multi-line header comment block without reading the whole file.
_GENERATED_BANNER_SCAN_LINES = 10


def is_generated_file(py_file: Path) -> bool:
    """
    Return True when *py_file*'s first few lines carry a generated-code banner
    (see :data:`GENERATED_FILE_MARKERS`).

    Style/debt predicates (R1, R2, R3, R6) and history metrics must not judge
    generated code by the same bar as hand-written code: a predicate only
    satisfiable by hand-editing generated output is a trap, since this project's
    own rules (``.claude/rules/bash-grammar.md``) forbid exactly that edit.
    """
    try:
        with py_file.open("r", encoding="utf-8", errors="replace") as fh:
            head = "".join(
                line for _, line in zip(range(_GENERATED_BANNER_SCAN_LINES), fh)
            )
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_FILE_MARKERS)


def iter_source_files(directory: Path = TOOLGUARD_DIR) -> List[Path]:
    """
    Return every ``*.py`` file under *directory* EXCLUDING generated code.

    Used by every style/debt predicate detector (R1/R2/R3/R6) and by
    :func:`build_import_graph` (shared by R5 and every ``--metrics`` history
    figure) -- see :func:`is_generated_file` for why. NOT used by
    :func:`check_layers`, which validates the real import graph including
    generated files: their imports are still real architecture, even though
    their internal style is exempt from the debt predicates.
    """
    return [p for p in iter_python_files(directory) if not is_generated_file(p)]


def list_generated_files(directory: Path = TOOLGUARD_DIR) -> List[str]:
    """
    Return every generated ``*.py`` file under *directory*, as toolguard-relative
    dotted paths, sorted. Reported explicitly by ``--predicates``/``--metrics`` so
    an exclusion is never silent -- silent exclusion is how the pyscn layer map
    degraded in the first place (see the module docstring).
    """
    return sorted(
        relative_module_path(p, directory)
        for p in iter_python_files(directory)
        if is_generated_file(p)
    )


def generated_repo_paths(
    directory: Path = TOOLGUARD_DIR, repo_root: Path = REPO_ROOT
) -> Set[str]:
    """
    Return every generated file's path relative to *repo_root*, POSIX-style
    (``"toolguard/parser/bash_parser.py"``) -- matching the path spelling
    ``--metrics`` gets from ``git diff-tree --name-only``, so history-based
    figures can exclude generated files the same way ``--predicates``'
    detectors do, rather than counting a file nobody could have hand-edited
    toward "how coupled is this codebase".
    """
    return {
        p.resolve().relative_to(repo_root.resolve()).as_posix()
        for p in iter_python_files(directory)
        if is_generated_file(p)
    }


def relative_module_path(py_file: Path, package_root: Path = TOOLGUARD_DIR) -> str:
    """
    Return *py_file*'s dotted path relative to *package_root*, e.g.
    ``toolguard/tools/decision.py`` -> ``"tools.decision"``.

    ``__init__.py`` maps to its containing package (``toolguard/tools/__init__.py``
    -> ``"tools"``); *package_root*'s own ``__init__.py`` maps to ``""`` -- it is
    the container, not a layer member, and callers should treat that specially.
    """
    rel = py_file.resolve().relative_to(package_root.resolve())
    parts = list(rel.parts)
    if parts[-1] == "__init__.py":
        parts = parts[:-1]
    else:
        parts[-1] = parts[-1][: -len(".py")]
    return ".".join(parts)


def first_segment(rel_dotted: str) -> str:
    """Return the first dotted segment of *rel_dotted*, or ``""`` for the root."""
    return rel_dotted.split(".", 1)[0] if rel_dotted else ""


def resolve_toolguard_import(
    module_name: Optional[str], level: int, importer_rel: str
) -> Optional[str]:
    """
    Resolve an ``import``/``from`` statement to a toolguard-relative dotted path.

    Args:
        module_name: The ``module`` part of an ``ast.ImportFrom`` (``None`` for a
            bare relative ``from . import x``), or the dotted name of an
            ``ast.Import`` alias.
        level: The ``ast.ImportFrom.level`` (0 for absolute, N for N leading dots).
            ``0`` for a plain ``ast.Import``.
        importer_rel: The toolguard-relative dotted path of the importing module
            (from :func:`relative_module_path`), used to resolve relative imports.

    Returns:
        The imported module's path relative to ``toolguard`` (e.g. ``"tools.decision"``,
        or ``""`` for the ``toolguard`` package itself), or ``None`` if the import
        does not target anything inside ``toolguard`` at all (stdlib/third-party).
    """
    if level == 0:
        if module_name is None:
            return None
        if module_name == "toolguard":
            return ""
        if module_name.startswith("toolguard."):
            return module_name[len("toolguard.") :]
        return None
    # Relative import: level dots strip that many trailing segments from the
    # importer's own package (an importer that is itself a leaf module, i.e.
    # has no dot, has an implicit trailing package segment of its own dir).
    importer_parts = importer_rel.split(".") if importer_rel else []
    # A module's own package is its parts minus the module name itself.
    package_parts = importer_parts[:-1] if importer_parts else []
    # level=1 means "from the importer's own package"; each extra level strips one more.
    strip = level - 1
    base_parts = (
        package_parts[: len(package_parts) - strip]
        if strip <= len(package_parts)
        else []
    )
    if module_name:
        base_parts = base_parts + module_name.split(".")
    return ".".join(base_parts)


@dataclass(frozen=True)
class ImportEdge:
    """One import found in the AST, resolved to toolguard-relative module paths."""

    importer: str  # toolguard-relative dotted path of the file doing the import
    imported: str  # toolguard-relative dotted path of the imported module
    line: int
    is_local: bool  # True when the Import/ImportFrom node is NOT at module top level


def _is_module_level(node: ast.AST, tree: ast.Module) -> bool:
    """Return True when *node* is a direct child of the module body (not nested)."""
    return node in tree.body


def extract_toolguard_imports(
    py_file: Path, package_root: Path = TOOLGUARD_DIR
) -> List[ImportEdge]:
    """
    Parse *py_file* and return every import that resolves to another module
    under *package_root*, at ANY nesting depth (module level or function-local)
    -- a function-local import is exactly the shape of the known
    hook.py<->tools.decision cycle, so restricting to module-level imports
    would miss it.
    """
    source = py_file.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(py_file))
    importer_rel = relative_module_path(py_file, package_root)
    edges: List[ImportEdge] = []
    for node in ast.walk(tree):
        is_local = not _is_module_level(node, tree)
        if isinstance(node, ast.Import):
            for alias in node.names:
                target = resolve_toolguard_import(alias.name, 0, importer_rel)
                if target is not None and target != importer_rel:
                    edges.append(
                        ImportEdge(importer_rel, target, node.lineno, is_local)
                    )
        elif isinstance(node, ast.ImportFrom):
            target = resolve_toolguard_import(node.module, node.level, importer_rel)
            if target is not None and target != importer_rel:
                edges.append(ImportEdge(importer_rel, target, node.lineno, is_local))
    return edges


# =============================================================================
# .pyscn.toml architecture parsing
# =============================================================================


@dataclass(frozen=True)
class LayerDef:
    """One ``[[architecture.layers]]`` entry."""

    name: str
    packages: Tuple[str, ...]


@dataclass(frozen=True)
class LayerRule:
    """One ``[[architecture.rules]]`` entry: what *from_layer* may import from."""

    from_layer: str
    allow: Tuple[str, ...]


@dataclass(frozen=True)
class ArchitectureConfig:
    """Parsed ``[architecture]`` block of ``.pyscn.toml``."""

    layers: Tuple[LayerDef, ...]
    rules: Tuple[LayerRule, ...]

    def package_to_layer(self) -> Dict[str, str]:
        """Return a ``{first-path-segment: layer name}`` map built from ``layers``."""
        mapping: Dict[str, str] = {}
        for layer in self.layers:
            for package in layer.packages:
                mapping[package] = layer.name
        return mapping

    def allow_for(self, layer_name: str) -> Tuple[str, ...]:
        """Return the set of layers *layer_name* is allowed to import from."""
        for rule in self.rules:
            if rule.from_layer == layer_name:
                return rule.allow
        return ()


def parse_architecture_config(pyscn_toml_path: Path = PYSCN_TOML) -> ArchitectureConfig:
    """Parse the ``[architecture]`` block of *pyscn_toml_path* via ``tomllib``."""
    with pyscn_toml_path.open("rb") as fh:
        data = tomllib.load(fh)
    arch = data.get("architecture", {})
    layers = tuple(
        LayerDef(name=entry["name"], packages=tuple(entry.get("packages", [])))
        for entry in arch.get("layers", [])
    )
    rules = tuple(
        LayerRule(from_layer=entry["from"], allow=tuple(entry.get("allow", [])))
        for entry in arch.get("rules", [])
    )
    return ArchitectureConfig(layers=layers, rules=rules)


# =============================================================================
# --layers
# =============================================================================


@dataclass
class LayerReport:
    """Result of :func:`check_layers`."""

    unmapped: List[str] = field(default_factory=list)
    multiply_mapped: Dict[str, List[str]] = field(default_factory=dict)
    module_layer: Dict[str, str] = field(default_factory=dict)
    violations: List[Dict[str, object]] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        """True when there is no completeness or direction problem."""
        return not self.unmapped and not self.multiply_mapped and not self.violations


def check_layers(
    toolguard_dir: Path = TOOLGUARD_DIR, arch: Optional[ArchitectureConfig] = None
) -> LayerReport:
    """
    Validate every module under *toolguard_dir* against *arch* (or the parsed
    ``.pyscn.toml`` if omitted). See the module docstring's ``--layers`` section.
    """
    if arch is None:
        arch = parse_architecture_config()
    package_map = arch.package_to_layer()
    report = LayerReport()

    py_files = list(iter_python_files(toolguard_dir))
    rel_paths: Dict[Path, str] = {}
    for py_file in py_files:
        rel = relative_module_path(py_file, toolguard_dir)
        if rel == "":
            continue  # the toolguard/__init__.py container itself
        rel_paths[py_file] = rel
        seg = first_segment(rel)
        matches = [layer for pkg, layer in package_map.items() if pkg == seg]
        if not matches:
            report.unmapped.append(rel)
        elif len(matches) > 1:
            report.multiply_mapped[rel] = matches
        else:
            report.module_layer[rel] = matches[0]

    for py_file in py_files:
        rel = rel_paths.get(py_file)
        if rel is None or rel not in report.module_layer:
            continue
        source_layer = report.module_layer[rel]
        allowed = set(arch.allow_for(source_layer))
        for edge in extract_toolguard_imports(py_file, toolguard_dir):
            if edge.imported == "":
                continue  # importing the toolguard package itself carries no layer info
            target_layer = report.module_layer.get(edge.imported)
            if target_layer is None:
                continue  # target itself unmapped; already reported separately
            if target_layer not in allowed:
                report.violations.append(
                    {
                        "source_module": rel,
                        "source_layer": source_layer,
                        "target_module": edge.imported,
                        "target_layer": target_layer,
                        "line": edge.line,
                        "local_import": edge.is_local,
                    }
                )
    return report


def render_layers_text(report: LayerReport) -> str:
    """Render *report* as human-readable text."""
    lines = ["=== --layers: completeness ==="]
    if report.unmapped:
        lines.append(f"UNMAPPED ({len(report.unmapped)}) -- matches zero layers:")
        for mod in report.unmapped:
            lines.append(f"  - {mod}")
    else:
        lines.append("All modules map to exactly one layer.")
    if report.multiply_mapped:
        lines.append(
            f"MULTIPLY-MAPPED ({len(report.multiply_mapped)}) -- matches more than one layer:"
        )
        for mod, layers in report.multiply_mapped.items():
            lines.append(f"  - {mod}: {', '.join(layers)}")

    lines.append("")
    lines.append("=== --layers: direction ===")
    if report.violations:
        lines.append(f"VIOLATIONS ({len(report.violations)}):")
        for v in report.violations:
            local = " [local import]" if v["local_import"] else ""
            lines.append(
                f"  - {v['source_module']} ({v['source_layer']}) -> "
                f"{v['target_module']} ({v['target_layer']}) at line {v['line']}{local}"
            )
    else:
        lines.append("No cross-layer direction violations.")
    return "\n".join(lines)


# =============================================================================
# --predicates: shared import-graph helpers (R5, R6, metrics fan-in)
# =============================================================================


def build_import_graph(toolguard_dir: Path = TOOLGUARD_DIR) -> Dict[str, Set[str]]:
    """
    Build ``{module: {modules it imports}}`` for every module under *toolguard_dir*.

    Nodes are toolguard-relative dotted paths (:func:`relative_module_path`); the
    root ``toolguard/__init__.py`` (``""``) is excluded as a node. Generated
    files (:func:`is_generated_file`) are excluded from the NODE set (they are
    not judged for fan-in/cycles/co-change) but a generated file importing a
    real module still isn't possible to see from here either way, since it is
    simply not scanned -- see the module docstring's generated-code section.
    """
    graph: Dict[str, Set[str]] = defaultdict(set)
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        if rel == "":
            continue
        graph.setdefault(rel, set())
        for edge in extract_toolguard_imports(py_file, toolguard_dir):
            if edge.imported and edge.imported != rel:
                graph[rel].add(edge.imported)
    return dict(graph)


def tarjan_scc(graph: Dict[str, Set[str]]) -> List[List[str]]:
    """
    Return the strongly connected components of *graph* (Tarjan's algorithm).

    Nodes referenced only as import targets (no outgoing edges of their own)
    are included with an empty adjacency set. A component of size > 1 is an
    import cycle; a component of size 1 is a cycle only if the node imports
    itself (excluded upstream by :func:`build_import_graph`).
    """
    index_counter = [0]
    stack: List[str] = []
    on_stack: Set[str] = set()
    indices: Dict[str, int] = {}
    lowlink: Dict[str, int] = {}
    result: List[List[str]] = []
    all_nodes = set(graph.keys()) | {n for targets in graph.values() for n in targets}

    def strongconnect(node: str) -> None:
        """Visit *node* in Tarjan's DFS, closing a component when a root is found."""
        indices[node] = index_counter[0]
        lowlink[node] = index_counter[0]
        index_counter[0] += 1
        stack.append(node)
        on_stack.add(node)
        for target in graph.get(node, ()):
            if target not in indices:
                strongconnect(target)
                lowlink[node] = min(lowlink[node], lowlink[target])
            elif target in on_stack:
                lowlink[node] = min(lowlink[node], indices[target])
        if lowlink[node] == indices[node]:
            component = []
            while True:
                w = stack.pop()
                on_stack.discard(w)
                component.append(w)
                if w == node:
                    break
            result.append(component)

    sys.setrecursionlimit(max(sys.getrecursionlimit(), len(all_nodes) * 4 + 1000))
    for node in sorted(all_nodes):
        if node not in indices:
            strongconnect(node)
    return result


def fan_in(graph: Dict[str, Set[str]]) -> Counter:
    """Return ``{module: number of distinct toolguard modules importing it}``."""
    counts: Counter = Counter()
    for _source, targets in graph.items():
        for target in targets:
            counts[target] += 1
    return counts


def longest_dependency_chain(graph: Dict[str, Set[str]]) -> List[str]:
    """
    Return one longest simple path through the import DAG obtained by
    condensing every strongly-connected component of *graph* into one node
    (a cycle has no finite "longest path" of its own, so it must be collapsed
    before this makes sense).
    """
    components = tarjan_scc(graph)
    comp_of: Dict[str, int] = {}
    for i, comp in enumerate(components):
        for node in comp:
            comp_of[node] = i
    condensed: Dict[int, Set[int]] = defaultdict(set)
    for source, targets in graph.items():
        for target in targets:
            if comp_of[source] != comp_of[target]:
                condensed[comp_of[source]].add(comp_of[target])
    all_ids = set(comp_of.values())

    memo: Dict[int, int] = {}

    def longest_from(cid: int) -> int:
        """Return the longest downstream hop-count from condensed node *cid*, memoized."""
        if cid in memo:
            return memo[cid]
        best = 0
        for nxt in condensed.get(cid, ()):
            best = max(best, 1 + longest_from(nxt))
        memo[cid] = best
        return best

    sys.setrecursionlimit(max(sys.getrecursionlimit(), len(all_ids) * 4 + 1000))
    best_len = -1
    best_start: Optional[int] = None
    for cid in all_ids:
        length = longest_from(cid)
        if length > best_len:
            best_len = length
            best_start = cid
    if best_start is None:
        return []
    chain_ids = [best_start]
    current = best_start
    while True:
        nxts = [n for n in condensed.get(current, ()) if memo[n] == memo[current] - 1]
        if not nxts:
            break
        current = nxts[0]
        chain_ids.append(current)
    # Render each condensed node back to its member module names (joined with "=" for a cycle).
    return ["=".join(sorted(components[cid])) for cid in chain_ids]


# =============================================================================
# --predicates: R1 -- one verdict type
# =============================================================================

VERDICT_NAME_RE_WORDS = ("decision", "resolution", "verdict")

#: Packages the TOO-45 ticket explicitly puts OUT OF SCOPE ("Out of scope,
#: unchanged: ... toolguard/parser/ including the generated parser" -- the
#: execution plan). A class living there (e.g. LeafCommand,
#: UndecidableSegment -- both hand-written; TreeNode, generated, already
#: excluded separately by :func:`iter_source_files`) is not evidence toward or
#: against "one verdict type end-to-end", because this ticket is not touching
#: that package at all. R1 is the only predicate this applies to today -- R5's
#: cycle check and R6's private-import check both have their own, different
#: reasons to look at (or past) parser/, so this is deliberately NOT a global
#: exclusion list.
R1_OUT_OF_SCOPE_PACKAGES = ("parser",)


def r1_out_of_scope_modules(toolguard_dir: Path = TOOLGUARD_DIR) -> List[str]:
    """
    Return every toolguard-relative module (including generated ones) under an
    :data:`R1_OUT_OF_SCOPE_PACKAGES` package, for explicit reporting -- an
    exclusion the operator can't see is indistinguishable from a bug.
    """
    return sorted(
        relative_module_path(p, toolguard_dir)
        for p in iter_python_files(toolguard_dir)
        if first_segment(relative_module_path(p, toolguard_dir))
        in R1_OUT_OF_SCOPE_PACKAGES
    )


def find_verdict_types(toolguard_dir: Path = TOOLGUARD_DIR) -> List[Dict[str, object]]:
    """
    Return every class whose name suggests it represents a permission verdict.

    Skips generated files and :data:`R1_OUT_OF_SCOPE_PACKAGES` -- see
    :func:`iter_source_files` and :data:`R1_OUT_OF_SCOPE_PACKAGES`.
    """
    found = []
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        if first_segment(rel) in R1_OUT_OF_SCOPE_PACKAGES:
            continue
        tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and any(
                w in node.name.lower() for w in VERDICT_NAME_RE_WORDS
            ):
                found.append({"class": node.name, "module": rel, "line": node.lineno})
    return found


def find_iter_shims(toolguard_dir: Path = TOOLGUARD_DIR) -> List[Dict[str, object]]:
    """
    Return every class defining ``__iter__`` (a tuple-compatibility shim, by
    convention in this codebase -- see :class:`~toolguard.resolve.BashResolution`),
    together with every call site that tuple-unpacks a call to a function
    whose body directly constructs that class (a heuristic "producer" link:
    exact call-graph tracing needs type inference this AST-only tool doesn't
    do, but catches the common ``result = Producer(...)`` / ``return Producer(...)``
    shape used throughout this codebase).

    Skips generated files and :data:`R1_OUT_OF_SCOPE_PACKAGES` when collecting
    ``__iter__``-defining classes (pass 1 below) -- see :func:`find_verdict_types`.
    Trees are still parsed for every in-scope file for the producer/caller
    passes, since a caller of an in-scope shim could live anywhere in scope.
    """
    shims: List[Dict[str, object]] = []
    producers_by_class: Dict[str, Set[str]] = defaultdict(set)

    # Pass 1: parse every in-scope file once (trees cached for pass 2) and
    # record every class defining __iter__ -- a producer function may live in
    # a different module than a caller, so the class map must be complete
    # before pass 2 looks for producers/callers.
    trees: Dict[str, ast.Module] = {}
    class_defs: Dict[str, Dict[str, object]] = {}
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
        trees[rel] = tree
        if first_segment(rel) in R1_OUT_OF_SCOPE_PACKAGES:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                has_iter = any(
                    isinstance(child, ast.FunctionDef) and child.name == "__iter__"
                    for child in node.body
                )
                if has_iter:
                    class_defs[node.name] = {
                        "class": node.name,
                        "module": rel,
                        "line": node.lineno,
                    }

    # Pass 2a: a function is a "producer" of ClassName when its body directly
    # constructs it (``ClassName(...)`` anywhere inside), the common
    # construct-and-return shape used throughout this codebase.
    for rel, tree in trees.items():
        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            for inner in ast.walk(node):
                if (
                    isinstance(inner, ast.Call)
                    and isinstance(inner.func, ast.Name)
                    and inner.func.id in class_defs
                ):
                    producers_by_class[inner.func.id].add(node.name)

    # Pass 2b: a caller of the shim tuple-unpacks the result of a producer call.
    callers: Dict[str, List[Dict[str, object]]] = defaultdict(list)
    for rel, tree in trees.items():
        for node in ast.walk(tree):
            targets = None
            call = None
            if isinstance(node, ast.Assign) and len(node.targets) == 1:
                target = node.targets[0]
                if isinstance(target, (ast.Tuple, ast.List)) and len(target.elts) >= 2:
                    targets = target.elts
                    call = node.value
            elif isinstance(node, ast.For):
                if (
                    isinstance(node.target, (ast.Tuple, ast.List))
                    and len(node.target.elts) >= 2
                ):
                    targets = node.target.elts
                    call = node.iter
            if targets is None or not isinstance(call, ast.Call):
                continue
            func = call.func
            func_name = (
                func.id
                if isinstance(func, ast.Name)
                else (func.attr if isinstance(func, ast.Attribute) else None)
            )
            if func_name is None:
                continue
            for class_name, producer_funcs in producers_by_class.items():
                if func_name in producer_funcs and class_name in class_defs:
                    callers[class_name].append(
                        {"module": rel, "line": node.lineno, "unpack_via": func_name}
                    )

    for class_name, info in class_defs.items():
        shims.append({**info, "callers": callers.get(class_name, [])})
    return shims


# =============================================================================
# --predicates: R2 -- ToolPatternLayer parallel arrays
# =============================================================================


def find_parallel_arrays(
    toolguard_dir: Path = TOOLGUARD_DIR, class_name: str = "ToolPatternLayer"
) -> List[Dict[str, object]]:
    """
    Return the ``(base, base_entries)`` field pairs defined on *class_name* --
    the parallel-array shape R2 targets (see the class's own docstring:
    "for each of the three allow/deny/ask pairs, X[i] is always the
    wrapper-stripped form of X_entries[i].pattern -- same order, same
    membership, index-for-index").
    """
    groups: List[Dict[str, object]] = []
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == class_name:
                field_names = [
                    stmt.target.id
                    for stmt in node.body
                    if isinstance(stmt, ast.AnnAssign)
                    and isinstance(stmt.target, ast.Name)
                ]
                for name in field_names:
                    if name.endswith("_entries"):
                        continue
                    paired = f"{name}_entries"
                    if paired in field_names:
                        groups.append(
                            {
                                "class": class_name,
                                "module": rel,
                                "line": node.lineno,
                                "base_field": name,
                                "entries_field": paired,
                            }
                        )
    return groups


# =============================================================================
# --predicates: R3 -- reason-string parsing
# =============================================================================

#: Documented exception: this is the SINGLE canonical fallback-marker classifier
#: (see its own docstring -- "made this function public in the first place" to
#: stop this exact pattern being duplicated ad hoc elsewhere). It defines the
#: structured contract other code is meant to call into rather than re-parsing
#: reason text itself, so it is excluded from the R3 site count as the sanctioned
#: implementation, not a violation. Revisit when R3 actually lands -- at that
#: point this function's own reason-matching may become the thing R3 replaces.
R3_SANCTIONED_SITES = {("compound.py", "fallback_kind_for_reason")}

#: String methods that recover STRUCTURED DATA (a substring, a position, an
#: index) out of a reason-named string when called ON it, e.g. ``reason.split``
#: or ``reason_body.rsplit``. Widened from the original {split, startswith,
#: endswith} after a real false negative: ``part.rsplit(" -> ", 1)`` inside a
#: (since-removed) hook.py helper recovered a ``(sub_command, matched_rule)``
#: pair the original set could not see would-be-caught receivers for.
_REASON_STRING_METHODS = {
    "split",
    "rsplit",
    "startswith",
    "endswith",
    "partition",
    "rpartition",
    "rindex",
    "index",
    "find",
}

#: ``re`` methods whose reason-bearing operand is typically an ARGUMENT, not
#: the receiver -- ``_COMPOUND_MATCH_PATTERN.match(reason)`` (a compiled
#: pattern's own method) and ``re.match(pattern, reason)`` (the module
#: function) both put ``reason`` in the argument list, never in the receiver
#: name, which is exactly the shape the original detector could not see: it
#: only ever looked at the receiver.
_REASON_REGEX_METHODS = {"match", "search", "fullmatch"}


def _name_of(node: ast.expr) -> Optional[str]:
    """Return a Name's id or an Attribute's trailing attr, else None."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _is_reason_named(node: ast.expr) -> bool:
    """Return True when *node* is a Name/Attribute whose own name contains "reason"."""
    name = _name_of(node)
    return bool(name) and "reason" in name.lower()


def _enclosing_function_name(tree: ast.Module, target: ast.AST) -> Optional[str]:
    """Return the name of the nearest enclosing function/method of *target*, if any."""
    best: Optional[str] = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if target in ast.walk(node):
                best = node.name
    return best


def find_reason_parsing_sites(
    toolguard_dir: Path = TOOLGUARD_DIR,
) -> List[Dict[str, object]]:
    """
    Return every production site that extracts structured meaning from a
    ``reason``-named string, excluding :data:`R3_SANCTIONED_SITES`.

    Three shapes are detected, all keyed on "does some Name/Attribute whose
    OWN name contains 'reason' (case-insensitive) appear here" -- which is why
    a local reassignment (``reason_body = resolved.reason``) is still caught,
    since the new name itself contains "reason":

    1. A :data:`_REASON_STRING_METHODS` call (``.split``, ``.rsplit``, ...) on
       a reason-named RECEIVER, e.g. ``reason.split(...)``.
    2. A :data:`_REASON_REGEX_METHODS` call (``.match``/``.search``/
       ``.fullmatch``) with a reason-named ARGUMENT anywhere in the call,
       whether the receiver is ``re`` itself or a module-level compiled
       pattern (``_COMPOUND_MATCH_PATTERN.match(reason)``) -- the original
       detector only ever looked at the receiver and missed exactly this
       shape in production once already.
    3. An ``in`` membership test against a reason-named value
       (``"  [" in reason_body``).

    KNOWN LIMIT, stated rather than silently missed: this is name-based, not
    data-flow analysis. A value split out of a reason string into a
    differently-named local (e.g. ``for part in reason.split(...): ...
    part.rsplit(...)``) is not traced past that rename -- the ``reason.split``
    call itself is still caught, but a *further* parse of ``part`` is not,
    because nothing in "part" says "this came from a reason string".
    """
    sites: List[Dict[str, object]] = []
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        source = py_file.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(py_file))
        lines = source.splitlines()
        for node in ast.walk(tree):
            expr = None
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in _REASON_STRING_METHODS
                and _is_reason_named(node.func.value)
            ):
                expr = lines[node.lineno - 1].strip()
            elif (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in _REASON_REGEX_METHODS
                and any(_is_reason_named(arg) for arg in node.args)
            ):
                expr = lines[node.lineno - 1].strip()
            elif isinstance(node, ast.Compare) and any(
                isinstance(op, ast.In) for op in node.ops
            ):
                if any(_is_reason_named(c) for c in node.comparators):
                    expr = lines[node.lineno - 1].strip()
            if expr is None:
                continue
            func_name = _enclosing_function_name(tree, node)
            if (py_file.name, func_name) in R3_SANCTIONED_SITES:
                continue
            sites.append(
                {
                    "module": rel,
                    "line": node.lineno,
                    "expression": expr,
                    "function": func_name,
                }
            )
    # A single line can trip two different AST patterns (e.g. a `.split(...)`
    # call and an `in reason` check in the same conditional expression, as in
    # hook.py's `reason.split(...) if ": " in reason else None`) -- dedupe to
    # one reported site per (module, line) rather than double-counting.
    seen: Set[Tuple[str, int]] = set()
    unique_sites = []
    for site in sites:
        key = (site["module"], site["line"])
        if key in seen:
            continue
        seen.add(key)
        unique_sites.append(site)
    return unique_sites


# =============================================================================
# --predicates: R5 -- runtime/scripts leafness + cycles
# =============================================================================


def find_non_leaf_entry_points(
    graph: Dict[str, Set[str]],
    arch: ArchitectureConfig,
    layer_names: Sequence[str] = ("runtime", "scripts"),
) -> List[Dict[str, object]]:
    """
    Return every module in a layer named in *layer_names* that has fan-in > 0
    (something else in toolguard imports it), i.e. is NOT a leaf, with its
    importers. ``scripts`` is a package name, not a layer name in
    ``.pyscn.toml`` (it lives inside the ``tooling`` layer alongside ``tools``)
    -- resolved here by package membership, not by layer name, so both the
    ``runtime`` layer and the ``scripts`` package are covered as the predicate
    names them.
    """
    package_map = arch.package_to_layer()
    incoming: Dict[str, List[str]] = defaultdict(list)
    for source, targets in graph.items():
        for target in targets:
            incoming[target].append(source)

    results = []
    for module in sorted(graph.keys()):
        seg = first_segment(module)
        layer = package_map.get(seg)
        in_runtime = layer == "runtime"
        in_scripts = seg == "scripts"
        if not (in_runtime and "runtime" in layer_names) and not (
            in_scripts and "scripts" in layer_names
        ):
            continue
        importers = sorted(incoming.get(module, []))
        if importers:
            results.append(
                {
                    "module": module,
                    "layer_or_package": "scripts" if in_scripts else "runtime",
                    "importers": importers,
                }
            )
    return results


def find_import_cycles(graph: Dict[str, Set[str]]) -> List[List[str]]:
    """Return every strongly connected component of size > 1 (an import cycle)."""
    return [comp for comp in tarjan_scc(graph) if len(comp) > 1]


# =============================================================================
# --predicates: R6 -- private-name imports from the engine
# =============================================================================

R6_GUARDED_MODULES = {"config", "permissions", "compound", "resolve"}


def find_private_imports(
    toolguard_dir: Path = TOOLGUARD_DIR,
) -> List[Dict[str, object]]:
    """
    Return every ``tools/``/``scripts/`` import of a private (leading-underscore,
    non-dunder) name from :data:`R6_GUARDED_MODULES`. Skips generated files
    (moot in practice today -- nothing generated lives under ``tools/`` or
    ``scripts/`` -- but consistent with every other detector).
    """
    sites: List[Dict[str, object]] = []
    for py_file in iter_source_files(toolguard_dir):
        rel = relative_module_path(py_file, toolguard_dir)
        seg = first_segment(rel)
        if seg not in ("tools", "scripts"):
            continue
        tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ImportFrom):
                continue
            target = resolve_toolguard_import(node.module, node.level, rel)
            if target not in R6_GUARDED_MODULES:
                continue
            for alias in node.names:
                name = alias.name
                if name.startswith("_") and not (
                    name.startswith("__") and name.endswith("__")
                ):
                    sites.append(
                        {
                            "importer": rel,
                            "target_module": target,
                            "private_name": name,
                            "line": node.lineno,
                        }
                    )
    return sites


# =============================================================================
# --predicates: enrichment footprint (tracked diagnostic, not a predicate)
# =============================================================================


def find_enrichment_footprint(toolguard_dir: Path = TOOLGUARD_DIR) -> List[str]:
    """
    Return every production file referencing ``additional_context`` or
    ``additionalContext``. NOT a pass/fail predicate -- see the module
    docstring and the TOO-45 plan section 2: this is evidence about whether
    the canary will move, tracked so a flat count at a step boundary is a
    finding, not a silent non-event. Skips generated files.
    """
    hits = []
    for py_file in iter_source_files(toolguard_dir):
        text = py_file.read_text(encoding="utf-8")
        if "additional_context" in text or "additionalContext" in text:
            hits.append(relative_module_path(py_file, toolguard_dir))
    return hits


# =============================================================================
# --predicates: assembly
# =============================================================================


def compute_predicates(toolguard_dir: Path = TOOLGUARD_DIR) -> Dict[str, object]:
    """
    Compute every R-predicate's components plus the enrichment footprint.

    Two exclusions apply across every detector here and are reported
    explicitly rather than silently, per the module docstring's generated-code
    section: generated files (:func:`list_generated_files`) never count toward
    a style/debt predicate, since a predicate only satisfiable by hand-editing
    generated output is a trap, not evidence. R1 additionally excludes
    :data:`R1_OUT_OF_SCOPE_PACKAGES` (``toolguard/parser/``), which this
    ticket does not touch at all.
    """
    arch = parse_architecture_config()
    graph = build_import_graph(toolguard_dir)

    r3_sites = find_reason_parsing_sites(toolguard_dir)
    r1_types = find_verdict_types(toolguard_dir)
    r1_shims = find_iter_shims(toolguard_dir)
    r5_non_leaves = find_non_leaf_entry_points(graph, arch)
    r5_cycles = find_import_cycles(graph)
    r6_sites = find_private_imports(toolguard_dir)
    r2_groups = find_parallel_arrays(toolguard_dir)
    footprint = find_enrichment_footprint(toolguard_dir)
    generated = list_generated_files(toolguard_dir)

    return {
        "generated_files_excluded": {
            "count": len(generated),
            "files": generated,
            "reason": (
                "machine-generated (banner-detected, see is_generated_file); "
                "excluded from every style/debt predicate and from --metrics, "
                "never from --layers"
            ),
        },
        "R3": {
            "pass": len(r3_sites) == 0,
            "sites": r3_sites,
            "sanctioned_exclusions": sorted(
                f"{f}::{fn}" for f, fn in R3_SANCTIONED_SITES
            ),
        },
        "R1": {
            "pass": len(r1_shims) == 0,
            "verdict_types": r1_types,
            "iter_shims": r1_shims,
            "out_of_scope_excluded": {
                "modules": r1_out_of_scope_modules(toolguard_dir),
                "reason": (
                    "toolguard/parser/ is explicitly out of scope for TOO-45 "
                    "per the execution plan"
                ),
            },
        },
        "R5": {
            "pass": len(r5_non_leaves) == 0 and len(r5_cycles) == 0,
            "non_leaf_entry_points": r5_non_leaves,
            "cycles": r5_cycles,
        },
        "R6": {
            "pass": len(r6_sites) == 0,
            "sites": r6_sites,
        },
        "R2": {
            "pass": len(r2_groups) == 0,
            "parallel_array_groups": r2_groups,
        },
        "enrichment_footprint": {
            "count": len(footprint),
            "files": footprint,
        },
    }


def render_predicates_text(predicates: Dict[str, object]) -> str:
    """Render :func:`compute_predicates`' output as human-readable text."""
    lines = []
    gen = predicates["generated_files_excluded"]
    lines.append(
        f"=== generated files excluded ({gen['count']}) -- {gen['reason']} ==="
    )
    for f in gen["files"]:
        lines.append(f"  - {f}")
    lines.append("")
    for pid in ("R1", "R2", "R3", "R5", "R6"):
        data = predicates[pid]
        lines.append(f"=== {pid}: {'PASS' if data['pass'] else 'FAIL'} ===")
        if pid == "R3":
            for s in data["sites"]:
                lines.append(
                    f"  - {s['module']}:{s['line']} in {s['function']}(): {s['expression']}"
                )
            if data["sanctioned_exclusions"]:
                lines.append(
                    f"  (excluded as sanctioned: {', '.join(data['sanctioned_exclusions'])})"
                )
        elif pid == "R1":
            lines.append(f"  verdict-ish types ({len(data['verdict_types'])}):")
            for t in data["verdict_types"]:
                lines.append(f"    - {t['class']} ({t['module']}:{t['line']})")
            lines.append(f"  __iter__ shims ({len(data['iter_shims'])}):")
            for shim in data["iter_shims"]:
                lines.append(
                    f"    - {shim['class']} ({shim['module']}:{shim['line']}), callers: {len(shim['callers'])}"
                )
                for c in shim["callers"]:
                    lines.append(
                        f"        {c['module']}:{c['line']} via {c['unpack_via']}(...)"
                    )
            oos = data["out_of_scope_excluded"]
            if oos["modules"]:
                lines.append(
                    f"  (out of scope -- {oos['reason']}: {', '.join(oos['modules'])})"
                )
        elif pid == "R5":
            for nl in data["non_leaf_entry_points"]:
                lines.append(
                    f"  - {nl['module']} ({nl['layer_or_package']}) imported by: {', '.join(nl['importers'])}"
                )
            for cyc in data["cycles"]:
                lines.append(f"  - cycle: {' <-> '.join(cyc)}")
        elif pid == "R6":
            for s in data["sites"]:
                lines.append(
                    f"  - {s['importer']}:{s['line']} imports private `{s['private_name']}` from {s['target_module']}"
                )
        elif pid == "R2":
            for g in data["parallel_array_groups"]:
                lines.append(
                    f"  - {g['module']}:{g['class']}: {g['base_field']} / {g['entries_field']}"
                )
        lines.append("")
    ef = predicates["enrichment_footprint"]
    lines.append(
        f"=== enrichment footprint (tracked, not a predicate): {ef['count']} files ==="
    )
    for f in ef["files"]:
        lines.append(f"  - {f}")
    return "\n".join(lines)


# =============================================================================
# --metrics
# =============================================================================

ZONE_PREFIXES = (
    ("tools", "tools"),
    ("parser", "parser"),
    ("scripts", "scripts"),
    ("testing", "testing"),
)


def zone_of(rel_module: str) -> str:
    """Return the zone name for a toolguard-relative dotted module path."""
    seg = first_segment(rel_module)
    for prefix, zone in ZONE_PREFIXES:
        if seg == prefix:
            return zone
    return "core"


def zone_of_repo_path(repo_relative_path: str) -> str:
    """
    Return the zone name for a repo-relative ``toolguard/...`` path, e.g.
    ``"toolguard/tools/decision.py"`` -> ``"tools"``.

    Thin adapter from git's repo-relative path spelling to :func:`zone_of`'s
    toolguard-relative dotted-module spelling.
    """
    without_prefix = repo_relative_path[len("toolguard/") :]
    dotted = without_prefix.removesuffix(".py").replace("/", ".")
    return zone_of(dotted)


def _run_git(args: Sequence[str], repo_root: Path = REPO_ROOT) -> str:
    """
    Run a read-only git command against *repo_root* and return its stdout.

    *repo_root* defaults to this repo but is overridable so tests can point
    the whole ``--metrics``/``--guard`` machinery at a small synthetic git
    repo instead of asserting against this project's own history.
    """
    result = subprocess.run(
        ["git", *args], cwd=repo_root, capture_output=True, text=True, check=True
    )
    return result.stdout


@dataclass(frozen=True)
class LogicalChange:
    """One logical change: a ticket-tagged group of commits, or a lone untagged commit."""

    key: str  # "TOO-45" or "commit:<sha>" for an untagged commit
    files: Tuple[
        str, ...
    ]  # repo-relative paths touched, across every commit in the group


_TICKET_TOKEN_RE = re.compile(r"TOO-\d+")


def _ticket_token(message: str) -> Optional[str]:
    """Return the first ``TOO-\\d+`` token in *message*, or ``None``."""
    match = _TICKET_TOKEN_RE.search(message)
    return match.group(0) if match else None


def collect_logical_changes(
    max_commits: Optional[int] = None, repo_root: Path = REPO_ROOT
) -> List[LogicalChange]:
    """
    Group *repo_root*'s commit history into logical changes by the ``TOO-nn``
    ticket token in each commit's FULL message (subject + body); an untagged
    commit is its own singleton group. This is the dedup that defeats
    commit-splitting as a gaming vector -- grouping per commit would let an
    iteration hide co-change by spreading it across several small commits.

    One ``git log --format=%B`` and one ``git diff-tree --name-only`` per
    commit, rather than a single combined ``--name-only --pretty=format:``
    call: git does not cleanly delimit the message body from the file list in
    the combined form (a multi-line commit message and the file list are both
    newline-separated with no marker between them), and this repo's history
    (dozens, not thousands, of commits) makes the extra subprocess calls cheap
    for what is a dev-only, non-hot-path tool.
    """
    shas = _run_git(["log", "--format=%H"], repo_root=repo_root).splitlines()
    if max_commits:
        shas = shas[:max_commits]

    groups: Dict[str, List[str]] = defaultdict(list)
    order: List[str] = []
    for sha in shas:
        message = _run_git(["log", "-1", "--format=%B", sha], repo_root=repo_root)
        files = [
            f
            for f in _run_git(
                ["diff-tree", "--no-commit-id", "--name-only", "-r", sha],
                repo_root=repo_root,
            ).splitlines()
            if f
        ]
        token = _ticket_token(message)
        key = token if token else f"commit:{sha}"
        if key not in groups:
            order.append(key)
        groups[key].extend(files)

    return [
        LogicalChange(key=key, files=tuple(dict.fromkeys(groups[key]))) for key in order
    ]


def production_files(
    files: Iterable[str], excluded: FrozenSet[str] = frozenset()
) -> List[str]:
    """
    Filter *files* (repo-relative paths) down to production ``toolguard/*.py``
    files, dropping any path in *excluded* (repo-relative -- see
    :func:`generated_repo_paths`, which is what ``--metrics`` passes here so a
    generated file never counts toward co-change/fan-in/zone-confinement
    figures).
    """
    return [
        f
        for f in files
        if f.startswith("toolguard/") and f.endswith(".py") and f not in excluded
    ]


def _percentile(values: Sequence[int], pct: float) -> float:
    """Nearest-rank percentile (no interpolation) over sorted *values*."""
    if not values:
        return 0.0
    ordered = sorted(values)
    idx = min(len(ordered) - 1, max(0, int(round(pct / 100 * (len(ordered) - 1)))))
    return float(ordered[idx])


#: A pair trivially looks "100% coupled" the first time two files happen to land
#: in the same commit -- with only a handful of logical changes touching
#: production code so far, that single coincidence carries no signal. Requiring
#: the rarer file to have been touched at least this many times before reporting
#: a pair mirrors the decision log's own bar for what counted as evidence
#: (compound.py<->config.py/permissions.py, 6 observations each) and keeps this
#: list to repeated coupling rather than one big commit's incidental co-touch.
MIN_COUPLING_OBSERVATIONS = 3


def compute_metrics(
    max_commits: Optional[int] = None,
    min_coupling_observations: int = MIN_COUPLING_OBSERVATIONS,
    repo_root: Path = REPO_ROOT,
    toolguard_dir: Path = TOOLGUARD_DIR,
) -> Dict[str, object]:
    """
    Compute every history-based metric described in the module docstring.

    *repo_root*/*toolguard_dir* default to this project but are overridable so
    a test can point the whole computation at a small synthetic repo instead
    of asserting against this project's own history. Generated files
    (:func:`generated_repo_paths`) are excluded from every figure here -- a
    file nobody hand-edits should not count toward "how coupled is this
    codebase".
    """
    changes = collect_logical_changes(max_commits=max_commits, repo_root=repo_root)
    excluded = frozenset(generated_repo_paths(toolguard_dir, repo_root))
    prod_changes = [
        (c.key, production_files(c.files, excluded))
        for c in changes
        if production_files(c.files, excluded)
    ]

    co_change: Counter = Counter()
    partners: Dict[str, Set[str]] = defaultdict(set)
    file_touch_count: Counter = Counter()
    for _key, files in prod_changes:
        for f in files:
            file_touch_count[f] += 1
        for i, a in enumerate(files):
            for b in files[i + 1 :]:
                pair = tuple(sorted((a, b)))
                co_change[pair] += 1
                partners[a].add(b)
                partners[b].add(a)

    max_partner_file = max(partners, key=lambda f: len(partners[f]), default=None)
    coupled_100pct = []
    for (a, b), count in co_change.items():
        rarer = min(file_touch_count[a], file_touch_count[b])
        if rarer >= min_coupling_observations and count == rarer:
            coupled_100pct.append(
                {"pair": [a, b], "co_changes": count, "rarer_total": rarer}
            )
    coupled_100pct.sort(key=lambda d: -d["co_changes"])

    confined = 0
    for _key, files in prod_changes:
        zones = {zone_of_repo_path(f) for f in files}
        if len(zones) == 1:
            confined += 1
    pct_confined = 100.0 * confined / len(prod_changes) if prod_changes else 0.0

    files_per_change = [len(files) for _key, files in prod_changes]

    scripts_hubs = [
        {"file": f, "partners": len(partners[f])}
        for f in partners
        if f.startswith("toolguard/scripts/")
    ]
    scripts_hubs.sort(key=lambda d: -d["partners"])

    graph = build_import_graph(toolguard_dir)
    fan_in_counts = fan_in(graph)
    max_fan_in_module = fan_in_counts.most_common(1)[0] if fan_in_counts else None
    cycles = find_import_cycles(graph)
    chain = longest_dependency_chain(graph)

    return {
        "generated_files_excluded": sorted(excluded),
        "logical_changes": len(changes),
        "production_logical_changes": len(prod_changes),
        "max_co_change_partners": (
            {"file": max_partner_file, "count": len(partners[max_partner_file])}
            if max_partner_file
            else None
        ),
        "coupled_100pct_pairs": coupled_100pct,
        "pct_confined_to_one_zone": round(pct_confined, 1),
        "p90_production_files_per_change": _percentile(files_per_change, 90),
        "scripts_co_change_hubs": scripts_hubs,
        "max_module_fan_in": (
            {"module": max_fan_in_module[0], "fan_in": max_fan_in_module[1]}
            if max_fan_in_module
            else None
        ),
        "import_cycle_count": len(cycles),
        "import_cycles": cycles,
        "longest_dependency_chain": chain,
        "fan_in_caveat": (
            "Fan-in is measured but KNOWN MISLEADING on this codebase: permissions/compound/"
            "resolve show fan-in 2 (looking like leaves) while co-change shows them as the "
            "most entangled files in the repo (compound.py has never changed without both "
            "config.py and permissions.py). The import graph cannot see coupling routed "
            "through config -- do not read fan-in alone, and do not read it as evidence R6 "
            "succeeded. See coupled_100pct_pairs above for what fan-in misses."
        ),
    }


def render_metrics_text(metrics: Dict[str, object]) -> str:
    """Render :func:`compute_metrics`' output as human-readable text."""
    lines = ["=== --metrics ==="]
    gen = metrics["generated_files_excluded"]
    if gen:
        lines.append(f"generated files excluded ({len(gen)}): {', '.join(gen)}")
    lines.append(
        f"logical changes: {metrics['logical_changes']} total, {metrics['production_logical_changes']} touching production toolguard/*.py"
    )
    mc = metrics["max_co_change_partners"]
    lines.append(
        f"max co-change partners: {mc['file']} ({mc['count']} partners)"
        if mc
        else "max co-change partners: n/a"
    )
    all_pairs = metrics["coupled_100pct_pairs"]
    shown_pairs = all_pairs[:30]
    lines.append(
        f"100%-coupled pairs ({len(all_pairs)}, showing top {len(shown_pairs)} by co-change count; "
        f"--json for the full list):"
    )
    for p in shown_pairs:
        lines.append(
            f"  - {p['pair'][0]} <-> {p['pair'][1]} ({p['co_changes']}/{p['rarer_total']})"
        )
    lines.append(
        f"% logical changes confined to one zone: {metrics['pct_confined_to_one_zone']}"
    )
    lines.append(
        f"p90 production files per logical change: {metrics['p90_production_files_per_change']}"
    )
    lines.append(f"scripts co-change hubs ({len(metrics['scripts_co_change_hubs'])}):")
    for h in metrics["scripts_co_change_hubs"]:
        lines.append(f"  - {h['file']}: {h['partners']} partners")
    lines.append("")
    mf = metrics["max_module_fan_in"]
    lines.append(
        f"max module fan-in: {mf['module']} ({mf['fan_in']})"
        if mf
        else "max module fan-in: n/a"
    )
    lines.append(f"import cycle count: {metrics['import_cycle_count']}")
    for cyc in metrics["import_cycles"]:
        lines.append(f"  - cycle: {' <-> '.join(cyc)}")
    lines.append(
        f"longest dependency chain ({len(metrics['longest_dependency_chain'])} hops): "
        f"{' -> '.join(metrics['longest_dependency_chain'])}"
    )
    lines.append("")
    lines.append("CAVEAT: " + metrics["fan_in_caveat"])
    return "\n".join(lines)


# =============================================================================
# --guard
# =============================================================================

GUARD_FORBIDDEN_PATH_PARTS = ("logs",)
GUARD_FORBIDDEN_NAMES = {".env", ".claude.env"}
GUARD_FORBIDDEN_SUBSTRINGS = (
    ".claude/toolguard_hook.toml",
    ".claude/settings.json",
    ".claude/settings.local.json",
)


def _changed_paths_since(ref: str, repo_root: Path = REPO_ROOT) -> List[str]:
    """
    Return every repo-relative path touched relative to *ref*, including
    uncommitted (staged, unstaged, and untracked) changes -- the guard must
    catch in-progress iteration work, not just committed history.
    """
    tracked = _run_git(["diff", "--name-only", ref], repo_root=repo_root).splitlines()
    untracked = _run_git(
        ["ls-files", "--others", "--exclude-standard"], repo_root=repo_root
    ).splitlines()
    return sorted(set(tracked) | set(untracked))


def _is_forbidden_path(rel_path: str) -> bool:
    """Return True when *rel_path* (repo-relative) is in a guarded location."""
    parts = Path(rel_path).parts
    if parts and parts[0] in GUARD_FORBIDDEN_PATH_PARTS:
        return True
    if Path(rel_path).name in GUARD_FORBIDDEN_NAMES:
        return True
    if any(sub in rel_path for sub in GUARD_FORBIDDEN_SUBSTRINGS):
        return True
    return False


def _count_test_methods(source: str) -> int:
    """Count ``test_*`` functions/methods (unittest style) in *source* via AST."""
    tree = ast.parse(source)
    return sum(
        1
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and node.name.startswith("test_")
    )


def _test_files_at_ref(ref: str, repo_root: Path = REPO_ROOT) -> Dict[str, int]:
    """
    Return ``{repo-relative path: test-method count}`` for every ``test/**/*.py``
    file as it existed at *ref*, read via ``git show`` (read-only; no checkout).
    """
    listing = _run_git(
        ["ls-tree", "-r", "--name-only", ref, "--", "test"], repo_root=repo_root
    ).splitlines()
    counts: Dict[str, int] = {}
    for path in listing:
        if not path.endswith(".py"):
            continue
        source = _run_git(["show", f"{ref}:{path}"], repo_root=repo_root)
        counts[path] = _count_test_methods(source)
    return counts


def _test_files_now(repo_root: Path = REPO_ROOT) -> Dict[str, int]:
    """Return ``{repo-relative path: test-method count}`` for the current working tree."""
    counts: Dict[str, int] = {}
    test_dir = repo_root / "test"
    if not test_dir.is_dir():
        return counts
    for py_file in iter_python_files(test_dir):
        rel = str(py_file.relative_to(repo_root))
        counts[rel] = _count_test_methods(py_file.read_text(encoding="utf-8"))
    return counts


def _project_dependencies(pyproject_text: str) -> List[str]:
    """Return the ``[project].dependencies`` list from *pyproject_text*."""
    data = tomllib.loads(pyproject_text)
    return list(data.get("project", {}).get("dependencies", []))


# =============================================================================
# --guard: canary check -- are the loop's own guard rules actually loaded?
# =============================================================================
#
# WHY THIS EXISTS. The TOO-45 loop's safety net includes two permission files,
# neither of which is version-controlled IN THIS REPO:
#
#   - .claude/toolguard_hook.toml   -- a SYMLINK into a separate dotfiles repo,
#     where the TOO-45 <TEMPORARY> deny fences are deliberately left uncommitted
#   - ~/.toolguard/rules/git.rules.toml -- lives outside any repository at all
#
# If either is reverted, `git clean`d away in its own repo, or overwritten,
# the guard rules simply vanish. And critically: this project's
# no_match_fallback = "allow_with_no_warnings" means a MISSING deny rule does
# not raise an error -- it silently becomes a permission. Nothing else in this
# tool (or anywhere) would notice. Every other --guard check answers "did the
# diff do something forbidden"; this one answers a logically prior question:
# "are the forbidding rules even still loaded, right now, in the live hook."
#
# The only way to answer that honestly is to ask the live hook, not to read
# the rule files and hope they parse the way we expect -- so this evaluates a
# fixed CANARY SET through the real `toolguard --eval` binary (read-only; see
# toolguard/hook.py's `_run_eval_mode`) and compares the verdict it returns
# against what it must currently return. "Assume nothing is loaded because it
# was loaded once" -- there is no persistent toolguard process to go stale in
# the first place (fresh subprocess per invocation), but the RULE FILES
# backing it can still be lost between one guard run and the next.
#
# MAINTENANCE: this constant MUST be updated whenever the <TEMPORARY> fences in
# either rules file change. A mismatch reported by this check means ONE OF TWO
# THINGS, and this tool cannot tell you which: either the guard rules were
# genuinely lost (the failure this check exists to catch), or the rules were
# DELIBERATELY changed and this constant is now stale. The operator must look
# at both the rules files and this constant and decide -- do not "fix" a
# mismatch by blindly updating the constant to match whatever the hook now
# returns, that defeats the entire check.
#
# The allow cases matter as much as the deny cases: a canary set that only
# probes for denies would pass happily even if the rules over-reached and
# started denying ordinary work, since a false deny would also read as "deny"
# here. Verified correct against the live hook on this machine, 2026-08-04.

#: File-path tools use "file_path" in tool_input; everything else uses
#: "command". Kept as a small local constant (deliberately NOT imported from
#: toolguard.hook.FILE_PATH_TOOLS) -- this check treats the installed hook as
#: an external black box invoked via subprocess, the same way a real Claude
#: Code PreToolUse event would, rather than reaching into its internals.
_CANARY_FILE_TOOLS = frozenset({"Read", "Write", "Edit"})


@dataclass(frozen=True)
class CanaryCase:
    """One fixed (tool, target) probe and the verdict it must currently produce."""

    tool: str
    #: May contain "{repo}", substituted with the repo root at evaluation time.
    target_template: str
    expect: str  # "allow" | "deny" | "ask"


GUARD_CANARIES: Tuple[CanaryCase, ...] = (
    # Bash: TOO-45's git-relaxation fences (~/.toolguard/rules/git.rules.toml).
    CanaryCase("Bash", "git clean -fdx", "deny"),
    CanaryCase("Bash", "git stash", "deny"),
    CanaryCase("Bash", "git commit --amend", "deny"),
    CanaryCase("Bash", "git rm -r toolguard/tools", "deny"),
    CanaryCase("Bash", "git bisect start", "deny"),
    CanaryCase("Bash", "git commit -m x", "allow"),
    CanaryCase("Bash", "git stash list", "allow"),
    # File tools: .claude/toolguard_hook.toml's <TEMPORARY> deny fence.
    CanaryCase("Write", "{repo}/logs/probe.md", "deny"),
    CanaryCase("Edit", "{repo}/.claude/toolguard_hook.toml", "deny"),
    CanaryCase("Write", str(Path.home() / ".claude" / "settings.json"), "deny"),
    CanaryCase("Write", "{repo}/toolguard/compound.py", "allow"),
    CanaryCase("Read", "{repo}/logs/probe.md", "allow"),
)


def resolve_toolguard_binary() -> Optional[str]:
    """
    Resolve the toolguard hook binary for canary evaluation.

    Prefers ``~/.local/bin/toolguard`` (the ``uv tool install`` location this
    project documents), falling back to whatever ``toolguard`` resolves to on
    PATH. Returns ``None`` when neither is found -- callers must treat that as
    SKIP, not FAIL: a missing binary is an environment problem, not evidence
    the guard rules were lost.
    """
    local_bin = Path.home() / ".local" / "bin" / "toolguard"
    if local_bin.is_file():
        return str(local_bin)
    return shutil.which("toolguard")


def _run_canary_case(
    binary: str, case: CanaryCase, repo_root: Path, timeout: float = 15.0
) -> Tuple[Optional[str], Optional[str]]:
    """
    Evaluate *case* through *binary* in ``--eval`` (read-only) mode.

    Returns ``(actual_verdict, error)`` where exactly one is ``None``:
    *actual_verdict* is the ``permissionDecision`` string on success; *error*
    describes what went wrong (non-zero exit, timeout, unparseable output) so a
    canary failure is diagnosable rather than a bare "None != deny".
    """
    target = case.target_template.format(repo=repo_root)
    tool_input = (
        {"file_path": target}
        if case.tool in _CANARY_FILE_TOOLS
        else {"command": target}
    )
    event = {
        "session_id": "architecture-fitness-guard-canary",
        "hook_event_name": "PreToolUse",
        "tool_name": case.tool,
        "tool_input": tool_input,
        "cwd": str(repo_root),
    }
    try:
        result = subprocess.run(
            [binary, "--eval"],
            input=json.dumps(event),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return None, "timed out"
    except OSError as e:
        return None, f"failed to run binary: {e}"
    stream = (
        result.stdout if result.returncode == 0 else (result.stdout or result.stderr)
    )
    try:
        payload = json.loads(stream)
        verdict = payload["hookSpecificOutput"]["permissionDecision"]
    except json.JSONDecodeError, KeyError, TypeError:
        return None, f"unparseable output (exit {result.returncode}): {stream[:200]!r}"
    return verdict, None


def run_guard_canaries(
    repo_root: Path = REPO_ROOT, binary: Optional[str] = None
) -> Dict[str, object]:
    """
    Evaluate every :data:`GUARD_CANARIES` case through the live toolguard hook
    and compare against its expected verdict.

    Args:
        repo_root: Repo root substituted into each case's ``{repo}`` template.
        binary: Path to the toolguard binary to invoke. Defaults to
            :func:`resolve_toolguard_binary`'s result; overridable so tests can
            point this at a stub binary instead of the real installed one.

    Returns:
        A dict with ``skipped``/``skip_reason`` (when no binary could be
        resolved -- SKIP, not FAIL), ``mismatches`` (human-readable strings,
        one per failing case, naming target/expected/actual), and ``results``
        (every case's raw outcome, for ``--json`` consumers).
    """
    resolved_binary = binary if binary is not None else resolve_toolguard_binary()
    if resolved_binary is None:
        return {
            "skipped": True,
            "skip_reason": (
                "canary check SKIPPED: toolguard binary not found "
                "(tried ~/.local/bin/toolguard and PATH)"
            ),
            "mismatches": [],
            "results": [],
        }

    results: List[Dict[str, object]] = []
    mismatches: List[str] = []
    for case in GUARD_CANARIES:
        actual, error = _run_canary_case(resolved_binary, case, repo_root)
        target = case.target_template.format(repo=repo_root)
        results.append(
            {
                "tool": case.tool,
                "target": target,
                "expected": case.expect,
                "actual": actual,
                "error": error,
            }
        )
        if error is not None:
            mismatches.append(f"canary error: {case.tool} {target!r}: {error}")
        elif actual != case.expect:
            mismatches.append(
                f"canary mismatch: {case.tool} {target!r} expected "
                f"{case.expect!r}, got {actual!r}"
            )
    return {
        "skipped": False,
        "skip_reason": None,
        "mismatches": mismatches,
        "results": results,
    }


@dataclass
class GuardReport:
    """Result of :func:`run_guard`."""

    failures: List[str] = field(default_factory=list)
    #: Non-failing but important notices (e.g. the canary check being skipped)
    #: -- must still surface, never pass silently, without failing the guard
    #: for the wrong reason (a missing binary is not evidence of a lost rule).
    warnings: List[str] = field(default_factory=list)
    #: Every canary case's raw outcome, when the canary check ran at all.
    canary_results: List[Dict[str, object]] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        """True when nothing failed."""
        return not self.failures


def _apply_canary_results(
    report: GuardReport, repo_root: Path, binary: Optional[str]
) -> None:
    """
    Run :func:`run_guard_canaries` and fold its outcome into *report* in place:
    a skip becomes a warning (visible, non-failing), a mismatch becomes a
    failure, and every raw result is kept on the report for ``--json``.
    """
    canary = run_guard_canaries(repo_root=repo_root, binary=binary)
    if canary["skipped"]:
        report.warnings.append(canary["skip_reason"])
    else:
        report.failures.extend(canary["mismatches"])
    report.canary_results = canary["results"]


def run_guard(
    since: str = "HEAD",
    run_lint: bool = True,
    repo_root: Path = REPO_ROOT,
    only_canaries: bool = False,
    run_canaries: bool = True,
    canary_binary: Optional[str] = None,
) -> GuardReport:
    """
    Run every deterministic check described in the module docstring's
    ``--guard`` section and return a :class:`GuardReport`.

    Args:
        since: Git ref to compare the current state (including uncommitted
            changes) against. Defaults to ``HEAD``.
        run_lint: When False, skip the ``ruff``/``check_doc_links.py`` subprocess
            checks (used by the tool's own test suite, which must not depend
            on the ambient lint state of whatever the test happens to run in,
            and is meaningless against a synthetic fixture repo).
        repo_root: Repository root to guard. Defaults to this repo; overridable
            so tests can point every check at a small synthetic git repo.
        only_canaries: When True, run ONLY the canary check (CLI:
            ``--guard-canaries-only``) -- skips the diff/test-count/dependency/
            lint checks entirely, none of which are meaningful on their own.
        run_canaries: When False, skip the canary check. Used by the tool's own
            test suite so the diff/test-count/dependency checks can be tested
            without depending on a real installed toolguard binary or on this
            machine's real permission config.
        canary_binary: Path to the toolguard binary for the canary check.
            Defaults to :func:`resolve_toolguard_binary`'s result; overridable
            so tests can point it at a stub instead of the real installed one.
    """
    report = GuardReport()

    if only_canaries:
        if run_canaries:
            _apply_canary_results(report, repo_root=repo_root, binary=canary_binary)
        return report

    changed = _changed_paths_since(since, repo_root=repo_root)
    for rel_path in changed:
        abs_path = (repo_root / rel_path).resolve()
        try:
            abs_path.relative_to(repo_root.resolve())
        except ValueError:
            report.failures.append(f"file touched outside the repository: {rel_path}")
            continue
        if _is_forbidden_path(rel_path):
            report.failures.append(f"file touched in a guarded location: {rel_path}")

    ref_tests = _test_files_at_ref(since, repo_root=repo_root)
    now_tests = _test_files_now(repo_root=repo_root)
    deleted = sorted(set(ref_tests) - set(now_tests))
    for f in deleted:
        report.failures.append(f"test file deleted: {f}")
    ref_total = sum(ref_tests.values())
    now_total = sum(now_tests.values())
    if now_total < ref_total:
        report.failures.append(
            f"test count decreased: {ref_total} ({since}) -> {now_total} (current)"
        )

    try:
        ref_pyproject = _run_git(
            ["show", f"{since}:pyproject.toml"], repo_root=repo_root
        )
        ref_deps = set(_project_dependencies(ref_pyproject))
    except subprocess.CalledProcessError:
        ref_deps = set()
    now_deps = set(
        _project_dependencies(
            (repo_root / "pyproject.toml").read_text(encoding="utf-8")
        )
    )
    new_deps = now_deps - ref_deps
    if new_deps:
        report.failures.append(
            f"new pyproject.toml dependency: {', '.join(sorted(new_deps))}"
        )

    if run_lint:
        checks = [
            (["uv", "run", "ruff", "check", "."], "ruff check"),
            (["uv", "run", "ruff", "format", "--check", "."], "ruff format --check"),
            (
                ["uv", "run", "python", "tools/check_doc_links.py"],
                "tools/check_doc_links.py",
            ),
        ]
        for cmd, label in checks:
            result = subprocess.run(cmd, cwd=repo_root, capture_output=True, text=True)
            if result.returncode != 0:
                report.failures.append(f"{label} failed (exit {result.returncode})")

    if run_canaries:
        _apply_canary_results(report, repo_root=repo_root, binary=canary_binary)

    return report


def render_guard_text(report: GuardReport) -> str:
    """Render :func:`run_guard`'s output as human-readable text."""
    if report.ok:
        lines = ["=== --guard: PASS === (no violations)"]
    else:
        lines = [f"=== --guard: FAIL ({len(report.failures)} violation(s)) ==="]
        for f in report.failures:
            lines.append(f"  - {f}")
    if report.canary_results:
        lines.append(
            f"canaries: {len(report.canary_results)} evaluated against the live hook"
        )
    if report.warnings:
        lines.append(f"WARNINGS ({len(report.warnings)}):")
        for w in report.warnings:
            lines.append(f"  - {w}")
    return "\n".join(lines)


# =============================================================================
# CLI
# =============================================================================


def main(argv: Optional[Sequence[str]] = None) -> int:
    """
    Parse arguments and dispatch to the selected mode(s). Multiple modes may
    be combined in one invocation; each prints its own section.
    """
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument(
        "--layers",
        action="store_true",
        help="Validate the layer map (completeness + direction).",
    )
    parser.add_argument(
        "--predicates",
        action="store_true",
        help="Emit TOO-45 step predicate components.",
    )
    parser.add_argument(
        "--metrics",
        action="store_true",
        help="Emit history-based co-change/structure metrics.",
    )
    parser.add_argument(
        "--guard",
        action="store_true",
        help="Run the deterministic safety-inspector checks.",
    )
    parser.add_argument(
        "--guard-canaries-only",
        action="store_true",
        help=(
            "Run ONLY the guard's canary check (are the loop's own permission "
            "rules still loaded?) -- skips the diff/test-count/dependency/lint "
            "checks."
        ),
    )
    parser.add_argument(
        "--since",
        default="HEAD",
        help="Git ref for --guard's comparison base (default: HEAD).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Machine-readable JSON output instead of text.",
    )
    parser.add_argument(
        "--no-lint",
        action="store_true",
        help="With --guard, skip the ruff/check_doc_links.py subprocess checks.",
    )
    args = parser.parse_args(argv)

    if not any(
        [
            args.layers,
            args.predicates,
            args.metrics,
            args.guard,
            args.guard_canaries_only,
        ]
    ):
        parser.error(
            "at least one of --layers, --predicates, --metrics, --guard, "
            "--guard-canaries-only is required"
        )

    exit_code = 0
    payload: Dict[str, object] = {}

    if args.layers:
        report = check_layers()
        payload["layers"] = {
            "ok": report.ok,
            "unmapped": report.unmapped,
            "multiply_mapped": report.multiply_mapped,
            "violations": report.violations,
        }
        if not args.json:
            print(render_layers_text(report))
            print()
        if not report.ok:
            exit_code = 1

    if args.predicates:
        predicates = compute_predicates()
        payload["predicates"] = predicates
        if not args.json:
            print(render_predicates_text(predicates))
            print()

    if args.metrics:
        metrics = compute_metrics()
        payload["metrics"] = metrics
        if not args.json:
            print(render_metrics_text(metrics))
            print()

    if args.guard or args.guard_canaries_only:
        report = run_guard(
            since=args.since,
            run_lint=not args.no_lint,
            only_canaries=args.guard_canaries_only,
        )
        payload["guard"] = {
            "ok": report.ok,
            "failures": report.failures,
            "warnings": report.warnings,
            "canary_results": report.canary_results,
        }
        if not args.json:
            print(render_guard_text(report))
            print()
        if not report.ok:
            exit_code = 1

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
