#!/usr/bin/env python
"""
Detects machine-generated ``*.py`` files by content banner, never by filename:
a filename check silently stops recognising the next generated file added.
"""

from __future__ import annotations

from pathlib import Path

#: Substrings that mark a file as machine-generated, matched case-insensitively.
GENERATED_FILE_MARKERS = (
    "generated from",
    "do not edit",
    "@generated",
    "autogenerated",
)

#: How many leading lines to scan for a generated-code banner.
_GENERATED_BANNER_SCAN_LINES = 10


def is_generated_file(py_file: Path) -> bool:
    """True when *py_file*'s first few lines carry a
    :data:`GENERATED_FILE_MARKERS` banner. An unreadable file reads as False."""
    try:
        with py_file.open("r", encoding="utf-8", errors="replace") as fh:
            head = "".join(
                line for _, line in zip(range(_GENERATED_BANNER_SCAN_LINES), fh)
            )
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_FILE_MARKERS)
